# Generated by Django 5.1.1 on 2025-11-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='api_movie_title_f63d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['id'], name='api_movie_id_dc14ec_idx'),
        ),
    ]
